name: CI/CD

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    # Optional linting
    # - name: Lint
    #   run: npm run lint

    - name: Build
      run: npm run build

    # Optional testing
    # - name: Test
    #   run: npm test

    - name: Publish (on main branch)
      if: github.ref == 'refs/heads/main'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release

    - name: Publish (on next branch)
      if: github.ref == 'refs/heads/next'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release --branches next